class Description:
    REQ_TORQUE_STATE = 'Request torque state'
    BATT_VOLTAGE = 'Battery voltage'
    BATT_STATE = 'Battery state'
    BRAKE_PEDAL_STATE = 'Brake pedal state'
    BRAKE_PEDAL_VOLTAGE = 'Brake pedal pin voltage'
    GEAR_POSITION = 'Gear shifter position'
    GEAR_SH_PIN_1 = 'Gear shifter pin 1 voltage'
    GEAR_SH_PIN_2 = 'Gear shifter pin 2 voltage'
    ACC_PEDAL_STATE = 'Acceleration pedal state'
    ACC_PEDAL_VOLTAGE = 'Acceleration pedal voltage'
